version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: development.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build:
      context: ./server
      dockerfile: development.Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./server:/backend
      - /backend/node_modules
      #- localpath:destinationpath:cached  #bind mounts
    # environment:
    #   - APP_ENV=development
    #   - KEYCLOAK_SECRET=secret
    #   - KEYCLOAK_REALM=value
    #   - KEYCLOAK_URL=https://url
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


#docker-compose -f docker-compose.development.yml up 
#--build